### ISSUE TITLE
Setting generateLabelsUnits with Javascript not working

### ISSUE THREAD

**Issue by kla-ko** [toolcool-org/toolcool-range-slider#3]
I have the following setup:
```
import { useRef, useEffect } from 'react';
import './lib/tcrs-generated-labels.min.js';
import './lib/toolcool-range-slider.min.js'; 

export default function RangeSliderPro({ component, eventHandlers, appData, pageData, parentDataModel }) {
  
  const sliderRef = useRef(null);
  
  useEffect( ()=>{
    const slider = sliderRef.current;
    slider.value1 = 30;
    slider.generateLabels = true;
    slider.generateLabelsUnits = '%';

    return () => { 
      slider?.removeEventListener('change', onChange);
    }
    
  }, [] )
  
  return ( 
    <tc-range-slider ref={sliderRef}></tc-range-slider> 
  )
}
```
**Issue**: the statement ``slider.generateLabelsUnits = '%'`` shows no effect.

**Comment by toolcool-org** [comment]
Fixed.

**Comment by kla-ko** [comment]
Got it working now, but only by looking into your tests.
The point is, that you've introduced the property ``units``, instead of  ``generateLabelsUnits``, which would be consistent with ``generate-labels-units``. 

Regards,

**Comment by toolcool-org** [comment]
I have added it to the documentation in the "script" example on this page below the text "It is also possible to enable or disable generated labels programmatically:":
https://range-slider.toolcool.org/pages/auto-generated-labels.html

**Comment by toolcool-org** [comment]
generateLabelsUnits is indeed a better name, but it's kind of a breaking change. I don't think many people use this API now, so it's probably a good time to change it.

**Comment by kla-ko** [comment]
It would be better if all API properties can be derived from the ``<tc-range-slider``- properties.
``generate-labels`` --> ``generateLabels``
``generate-labels-units``--> ``generateLabelsUnits``, etc. 

If you want to stay compatible (no breaking change), just allow both API parameters, ``units`` and ``generateLabelsUnits``.

Do you want me to close this issue?

Regards,

**Comment by toolcool-org** [comment]
Just FYI - I added the following APIs:
slider.generateLabelsUnits = '%';
slider.generateLabelsTextColor = '#545454';
