### ISSUE TITLE
disable mousewheel events

### ISSUE THREAD

**Issue by bptarpley** [toolcool-org/toolcool-range-slider#6]
This is a great component and I'm excited to use it in my project. Unfortunately, my project involves hooking into mousewheel events quite extensively, and often the browser gets confused as to what the active component is. After interacting with the range slider, any subsequent mousewheel events move the slider (even if the mouse is no longer hovering over the range slider). Would it be possible to add an attribute like "keyboard-disabled" except specifically for turning off mousewheel events? If not, could you consider checking the keyboard-disabled attribute before reacting to mousewheel events? I assumed that would be the functionality given how mousewheel events are listed in the documentation under keyboard interaction. Many thanks in advance!

**Comment by appstruction** [comment]
+1

Great work by the way!

**Comment by toolcool-org** [comment]
The **mousewheel-disabled** attribute is added.
Docs: https://range-slider.toolcool.org/pages/touch-and-keyboard-support.html
Example page: https://github.com/toolcool-org/toolcool-range-slider/blob/main/examples/34-mousewheel-disabled.html

**Comment by bptarpley** [comment]
I have updated my library to the latest release and tested the new mousewheel-disabled attribute--it works great! Thank you for having addressed this so quickly :)

**Comment by toolcool-org** [comment]
You're welcome!
