### ISSUE TITLE
Formatting option

### ISSUE THREAD

**Issue by appstruction** [toolcool-org/toolcool-range-slider#7]
It would be very nice, to have the option to format a label value, for e.g. as a currency value with dots and fraction digits.

**Comment by toolcool-org** [comment]
I added a formatting option to the "Auto Generated Labels" plugin - https://range-slider.toolcool.org/pages/auto-generated-labels.html#custom-formatting

Example page is here - https://github.com/toolcool-org/toolcool-range-slider/blob/main/examples/35-autogenerated-labels-plugin-with-formatting.html
