### ISSUE TITLE
Formatting option for auto binding labels

### ISSUE THREAD

**Issue by pw-elfred** [toolcool-org/toolcool-range-slider#8]
Nice library, good job, thank you for providing this library. :-)

It would be very nice, to have a formatting-option for auto binding labels, like currency or percent or dimensions. Is this possible?

Thank you.

**Comment by toolcool-org** [comment]
Thank you for the feedback. There is "Auto Generated Labels" plugin that has such option - `generate-labels-units="%"`. It's better to use it for this purpose. The documentation is here: https://range-slider.toolcool.org/pages/auto-generated-labels.html

**Comment by pw-elfred** [comment]
The auto generated label does too much for my purpose. I only need min value in front and max value at the end, but auto generated label also adds the current position value on top of the slider.

**Comment by toolcool-org** [comment]
You can probably achieve it by adding currency / percent / dimensions before or after your placeholder. For example: 
https://codepen.io/toolcool/pen/abaYxyq

**Comment by toolcool-org** [comment]
Closing because there was no further response.
